baseURL = 'https://uvadmt.github.io/'
languageCode = 'en-us'
title = 'cs2120: Discrete Mathematics and Theory 1'
theme = "dmt1"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # Allow HTML rendering
      hardWraps = false # Disable hard wraps for newlines
      xhtml = false # Disable XHTML-compliant HTML output
  [markup.highlight]
    codeFences = true # Enable code fences
    lineNos = true # Show line numbers
    lineNumbersInTable = true # Show line numbers in tables
    style = "monokai" # Set syntax highlighting style
  [markup.tableOfContents]
    startLevel = 2 # Start table of contents at this heading level
    endLevel = 6 # End table of contents at this heading level

[params]
author = ""
shortTitle = "cs2120: DMT1"
introDescription = "DMT1 Spring 2025"
fullTitle = "cs2120: Discrete Math and Theory 1"
university = "University of Virginia"
semester = "Spring 2025"

dateFormat = "2 January 2006" # Default to "Jan 2, 2006".
canonifyurls = true
enableSearch = false
pygmentsUseClasses=true

enableMathNotation = true

[social]

